//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 514|@I@.@H@.FF@.@DA.EEA.AAA.@GB.@BB.@CB.@E@.@D@.@C@.@BA.@IA.GGA.HHB.@AB.@FB.BB@.AA@.@G@.@HA.@CA.@FA.DDB.@EB.IIB.@CC.@BC.@DC.AAD.FFD.IID.@EE.@GE.HHE.AAC.IIC.@HC.@GD.@BD.EED.@FE.@CE.@DE.GGC.FFC.@EC.CCD.@DD.@HD.@AE.@IE.BBE.@FF.@CF.IIF.@EG.@GG.@DG.@BH.@HH.@AH.HHF.@EF.@BF.@FG.AAG.CCG.@IH.DDH.@GH.@DF.GGF.AAF.IIG.HHG.@BG.CCH.@FH.@EH
        ///518|@C@.@F@.AA@.HHA.@BA.@IA.@GB.EEB.DDB.@H@.@G@.@B@.@DA.@EA.@AA.IIB.FFB.@CB.@D@.@E@.II@.FFA.GGA.@CA.@AB.BBB.HHB.AAC.CCC.@HC.@ID.@FD.BBD.@EE.@DE.GGE.@GC.@BC.@EC.@AD.@DD.@HD.FFE.@CE.@IE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EasyFalse {
            get {
                return ResourceManager.GetString("EasyFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 518|@F@.@C@.@I@.HHA.DDA.@GA.EEB.BBB.@AB.@E@.DD@.AA@.CCA.@BA.@FA.GGB.@IB.@HB.HH@.@B@.@G@.@EA.AAA.IIA.@FB.@DB.CCB.@IC.@EC.@BC.AAD.FFD.@HD.@CE.GGE.DDE.@CC.@HC.@FC.GGD.@ED.@DD.@BE.@AE.@IE.@GC.AAC.DDC.BBD.@ID.@CD.@HE.@FE.EEE.@AF.@FF.@CF.DDG.@HG.@BG.IIH.@EH.@GH.@BF.GGF.@EF.@IG.CCG.AAG.DDH.@HH.FFH.@DF.@IF.HHF.@FG.GGG.@EG.@AH.@CH.@BH
        ///510|@D@.@F@.@I@.HHA.@GA.@BA.@EB.@AB.@CB.@A@.@H@.GG@.@CA.FFA.@EA.@DB.BBB.IIB.@B@.CC@.EE@.AAA.@DA.@IA.@HB.@FB.GGB.HHC.EEC.@FC.@GD.@BD.DDD.@CE.@IE.@AE.@GC.@AC.DDC.@FD.@ID.CCD.@BE.@EE.HHE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EasyTrue {
            get {
                return ResourceManager.GetString("EasyTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 704|@E@.@F@.CC@.GGA.@HA.@BA.@AB.@DB.@IB.@B@.GG@.@A@.@FA.@DA.IIA.HHB.@EB.@CB.DD@.@I@.@H@.@CA.@AA.EEA.@FB.@BB.@GB.HHC.@BC.@FC.DDD.@ID.@GD.EEE.@CE.AAE.GGC.EEC.IIC.AAD.@BD.@CD.@DE.HHE.@FE.@AC.@CC.DDC.@HD.@ED.@FD.IIE.GGE.@BE.@CF.HHF.@GF.@IG.FFG.@DG.@BH.@AH.@EH.FFF.@AF.@EF.@BG.CCG.@HG.GGH.IIH.DDH.@IF.@DF.@BF.EEG.@GG.@AG.@CH.@FH.@HH
        ///821|@A@.GG@.@B@.@EA.@FA.@HA.@IB.@CB.DDB.@E@.@F@.CC@.@GA.IIA.@DA.@AB.@BB.@HB.@H@.@D@.II@.AAA.BBA.@CA.@GB.FFB.EEB.@DC.@AC.@GC.IID.CCD.@ED.@BE.@HE.FFE.@IC.@EC.@HC.@FD.@DD.BBD.@CE.AAE.@GE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ExtremelyHardFalse {
            get {
                return ResourceManager.GetString("ExtremelyHardFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1051|@A@.@E@.@C@.IIA.@FA.@BA.@HB.@DB.@GB.@B@.FF@.@H@.@GA.@EA.DDA.IIB.@CB.AAB.II@.@D@.@G@.CCA.HHA.@AA.@BB.@FB.EEB.@GC.BBC.@IC.@ED.@AD.@FD.DDE.@HE.@CE.HHC.@AC.@DC.@BD.@ID.CCD.@EE.@GE.@FE.@FC.@CC.EEC.@DD.@GD.@HD.@AE.IIE.@BE.DDF.GGF.@AF.@FG.@BG.@IG.@CH.@EH.@HH.@CF.HHF.FFF.AAG.@DG.EEG.@GH.@BH.@IH.@EF.@IF.@BF.@HG.CCG.@GG.@FH.@AH.@DH
        ///959|@B@.@D@.@G@.IIA.@HA.@FA.@CB.EEB.@AB.@C@.@A@.@F@.@GA.@DA.@EA.@HB.@BB.IIB.II@.@E@.@H@.@CA.@AA.@BA.@FB.@GB.@DB.@AC.@BC.@DC.EED.FFD.@CD.IIE.@HE.@GE.@EC.@FC.@IC.AAD.GGD.@HD.@BE.DDE.@C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ExtremelyHardTrue {
            get {
                return ResourceManager.GetString("ExtremelyHardTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 576|@E@.@A@.@F@.HHA.DDA.@BA.@CB.GGB.IIB.@D@.@G@.HH@.@CA.@FA.@IA.BBB.@AB.@EB.@I@.@B@.@C@.@GA.@AA.EEA.@HB.@DB.@FB.BBC.@DC.@GC.AAD.HHD.@FD.@EE.@IE.@CE.@CC.IIC.AAC.@ED.@BD.DDD.@FE.@HE.@GE.@HC.FFC.@EC.IID.@GD.@CD.@DE.BBE.@AE.@AF.EEF.@DF.@BG.@CG.GGG.IIH.FFH.@HH.GGF.CCF.BBF.@FG.@IG.@HG.@AH.@EH.DDH.FFF.@HF.@IF.@DG.@EG.@AG.@GH.@CH.@BH
        ///576|BB@.GG@.@C@.@AA.@IA.DDA.@HB.EEB.FFB.@I@.@E@.DD@.@FA.HHA.@CA.@AB.@BB.@GB.@F@.@A@.HH@.EEA.@GA.@BA.DDB.@IB.@CB.AAC.HHC.@EC.CCD.@FD.@ID.BBE.@GE.DDE.GGC.@CC.@BC.@DD.@AD.@ED.@IE.@FE.@HE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HardFalse {
            get {
                return ResourceManager.GetString("HardFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 697|@H@.@C@.@B@.IIA.@FA.@DA.@GB.AAB.@EB.@E@.@I@.@D@.@HA.@AA.@GA.@CB.@FB.BBB.FF@.GG@.AA@.@BA.@CA.EEA.DDB.@IB.@HB.@CC.@BC.@FC.@ED.DDD.@ID.@AE.@HE.@GE.IIC.@HC.EEC.AAD.@GD.FFD.@BE.CCE.@DE.AAC.@DC.@GC.@CD.@HD.@BD.@IE.@EE.FFE.DDF.@EF.@HF.@GG.IIG.@CG.@FH.@BH.AAH.@GF.@AF.@CF.@FG.BBG.HHG.EEH.@DH.@IH.BBF.@FF.IIF.@DG.@EG.@AG.HHH.@GH.@CH
        ///681|@E@.@B@.@F@.@GA.@DA.@AA.HHB.@CB.@IB.@D@.@H@.@G@.EEA.@IA.CCA.FFB.@AB.BBB.@I@.CC@.@A@.@FA.BBA.@HA.EEB.DDB.@GB.@HC.@IC.@EC.CCD.@AD.@GD.@DE.BBE.@FE.@CC.GGC.@BC.DDD.FFD.@ID.@AE.@EE.@HE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HardTrue {
            get {
                return ResourceManager.GetString("HardTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 564|@A@.EE@.@I@.BBA.FFA.@CA.@HB.@DB.@GB.@B@.@H@.@G@.@AA.EEA.DDA.IIB.@CB.@FB.@C@.@F@.@D@.IIA.@GA.@HA.BBB.AAB.EEB.FFC.@BC.@AC.@CD.@HD.GGD.@DE.@EE.@IE.@EC.GGC.@HC.@DD.IID.@AD.CCE.@FE.@BE.@DC.@IC.CCC.@FD.@BD.@ED.@AE.@GE.HHE.@HF.DDF.@FF.@EG.AAG.IIG.GGH.BBH.CCH.@GF.CCF.BBF.HHG.DDG.FFG.@EH.@IH.@AH.@IF.@AF.EEF.GGG.@CG.@BG.@FH.@HH.@DH
        ///534|@E@.@C@.II@.@DA.@GA.@FA.@BB.HHB.AAB.@A@.HH@.GG@.@BA.@IA.@EA.FFB.DDB.@CB.@D@.@F@.@B@.@HA.@AA.CCA.IIB.@GB.EEB.@BC.AAC.@CC.@ID.HHD.@DD.@GE.@EE.FFE.IIC.EEC.@HC.@CD.@FD.GGD.@DE.@AE.@BE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NormalFalse {
            get {
                return ResourceManager.GetString("NormalFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 594|@G@.@H@.FF@.EEA.@DA.@BA.@IB.AAB.CCB.@C@.@I@.@E@.FFA.@AA.@GA.HHB.BBB.@DB.@A@.@B@.@D@.@HA.@IA.@CA.EEB.@FB.@GB.HHC.@EC.GGC.@CD.@FD.@DD.@AE.@IE.@BE.@FC.@AC.CCC.@BD.@HD.@ID.@DE.GGE.EEE.@BC.DDC.@IC.GGD.@ED.@AD.FFE.@CE.HHE.@EF.@CF.@AF.@DG.GGG.@FG.@BH.@HH.IIH.@DF.FFF.@BF.@IG.CCG.HHG.@GH.EEH.@AH.@IF.@GF.HHF.@AG.@BG.@EG.@CH.@DH.FFH
        ///592|@H@.@F@.@B@.@IA.@GA.@CA.AAB.@EB.DDB.@C@.@G@.@D@.@EA.HHA.@AA.@BB.FFB.@IB.@E@.AA@.@I@.@BA.DDA.@FA.HHB.@GB.CCB.FFC.@CC.@EC.AAD.@ID.BBD.@DE.@HE.@GE.@IC.@DC.AAC.@GD.@ED.@HD.FFE.CCE.@BE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NormalTrue {
            get {
                return ResourceManager.GetString("NormalTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.9,Easy,494,False|0.0,0,5,False,0;0.1,0,7,False,0;0.2,0,1,False,0;0.3,9,9,True,1;0.4,0,6,False,1;0.5,0,2,False,1;0.6,3,3,True,2;0.7,8,8,True,2;0.8,0,4,False,2;1.0,2,2,True,0;1.1,0,4,False,0;1.2,0,9,False,0;1.3,0,3,False,1;1.4,0,7,False,1;1.5,8,8,True,1;1.6,0,1,False,2;1.7,6,6,True,2;1.8,5,5,True,2;2.0,0,6,False,0;2.1,0,8,False,0;2.2,3,3,True,0;2.3,0,4,False,1;2.4,5,5,True,1;2.5,0,1,False,1;2.6,9,9,True,2;2.7,0,2,False,2;2.8,7,7,True,2;3.0,9,9,True,3;3.1,0,6,False,3;3.2,2,2,True,3;3.3,0,5,False,4;3.4,0,1,Fa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PregeneratedPuzzles {
            get {
                return ResourceManager.GetString("PregeneratedPuzzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 635|@A@.@B@.@F@.EEA.GGA.CCA.DDB.@IB.@HB.HH@.@E@.@D@.@BA.@AA.IIA.@GB.@FB.@CB.CC@.@I@.@G@.HHA.@DA.@FA.@BB.@AB.@EB.@GC.@AC.@EC.@CD.BBD.@DD.@IE.HHE.@FE.@IC.@CC.@BC.@FD.@ED.@HD.AAE.@DE.GGE.DDC.@FC.HHC.GGD.IID.@AD.@CE.EEE.BBE.EEF.HHF.@IF.DDG.@CG.@GG.FFH.BBH.@AH.BBF.GGF.@AF.@IG.@FG.@EG.HHH.@CH.@DH.@FF.DDF.@CF.AAG.@HG.@BG.@EH.@GH.@IH
        ///642|@A@.CC@.DD@.@GA.@EA.@BA.IIB.@HB.@FB.BB@.@G@.@I@.@CA.HHA.FFA.@AB.@EB.@DB.@E@.HH@.FF@.@AA.IIA.@DA.@BB.@CB.@GB.CCC.@EC.@GC.@DD.AAD.HHD.@FE.@BE.@IE.@HC.@IC.@BC.@FD.@GD.@ED.@CE.DDE.@AE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VeryHardFalse {
            get {
                return ResourceManager.GetString("VeryHardFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 931|@F@.DD@.@G@.CCA.@BA.AAA.@HB.@EB.@IB.@I@.@B@.@A@.@HA.EEA.@GA.@CB.@FB.@DB.@E@.@C@.@H@.@IA.FFA.@DA.@GB.@AB.BBB.@BC.@HC.CCC.GGD.@AD.@ED.DDE.IIE.FFE.DDC.@GC.@IC.@FD.@CD.@BD.@EE.HHE.@AE.@AC.@EC.@FC.DDD.HHD.@ID.@BE.@GE.@CE.@GF.IIF.BBF.EEG.@DG.@FG.@AH.@CH.@HH.@CF.AAF.@EF.@BG.@IG.HHG.@FH.@DH.GGH.@HF.FFF.@DF.AAG.@GG.@CG.@IH.@BH.@EH
        ///810|@D@.@B@.@G@.HHA.@FA.@CA.AAB.@EB.IIB.@F@.@A@.II@.EEA.BBA.@DA.@CB.HHB.@GB.HH@.EE@.CC@.@GA.@IA.AAA.BBB.@FB.@DB.@CC.@GC.@DC.@FD.@HD.@ED.@IE.@BE.@AE.@BC.@FC.AAC.@DD.@GD.@ID.@HE.CCE.EEE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VeryHardTrue {
            get {
                return ResourceManager.GetString("VeryHardTrue", resourceCulture);
            }
        }
    }
}
